# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userexample.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11userexample.proto\"5\n\x04User\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\r\n\x05\x65mail\x18\x03 \x01(\t2\x89\x01\n\x12UserExampleService\x12\x1c\n\nCreateUser\x12\x05.User\x1a\x05.User\"\x00\x12\x19\n\x07GetUser\x12\x05.User\x1a\x05.User\"\x00\x12\x1c\n\nUpdateUser\x12\x05.User\x1a\x05.User\"\x00\x12\x1c\n\nDeleteUser\x12\x05.User\x1a\x05.User\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'userexample_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=21
  _USER._serialized_end=74
  _USEREXAMPLESERVICE._serialized_start=77
  _USEREXAMPLESERVICE._serialized_end=214
# @@protoc_insertion_point(module_scope)
